export default {
	annotations: {
		list: [
			{
				builtIn: 1,
				datasource: '-- Grafana --',
				enable: true,
				hide: true,
				iconColor: 'rgba(0, 211, 255, 1)',
				limit: 100,
				name: 'Annotations & Alerts',
				showIn: 0,
				type: 'dashboard',
			},
		],
	},
	editable: true,
	graphTooltip: 2,
	links: [],
	panels: [],
	refresh: '30s',
	schemaVersion: 22,
	style: 'dark',
	tags: [],
	templating: {},
	time: {
		from: 'now-1h',
		to: 'now',
	},
	timepicker: {
		refresh_intervals: [
			'5s',
			'10s',
			'30s',
			'1m',
			'5m',
			'15m',
			'30m',
			'1h',
			'2h',
			'1d',
		],
		time_options: ['5m', '15m', '1h', '6h', '12h', '24h', '2d', '7d', '30d'],
	},
	timezone: 'utc',
	version: 1,
};
